# General Settings
title = "FrostFire Images"
baseURL = "https://frostfireimages.ca/"

languageCode = "en-us"
theme = "glacier"
resourceDir = "resources"
paginate = 5
summaryLength = 50
DefaultContentLanguage = "en" # Site language. Available translations in the theme's `/i18n` directory.


# Menu Settings
[menu]
[[menu.main]]
    identifier = "Gallery"
    name = "Gallery"
    url = "/Gallery/"
  weight = 2
[[menu.main]]
    identifier = "Shop"
    name = "Shop"
    url = "/shop/"
    weight = 3
[[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 4
[[menu.main]]
  identifier = "contact"
  name = "Contact"
  url = "/contact/"
  weight = 5
 

# Main Settings
[params]
defaultLogo = "Transparent logo Alt Black.png"
defaultKeywords = ["Photography", "Professional Photographer", "Art", "Action Sports Photography", "google analytics", "Action Sports", "Photography portfolio", "High quality Poster", "Landscapes", "Wildlife", "Skateboarding", "Frostfireimages"]
defaultDescription = "Frost Fire Images"
dateFormat = "January 2, 2006"
authorName = "Mountain-Themes"
disqusComments = "" #YOUR DISQUS COMMENTS SHORTNAME
formspreeFormKey = "mbljypnb" 
reCAPTCHAKey = "6LdJWXUqAAAAADqn1_5lx5GsGG6R_ZP38GML8U6Q" #YOUR reCAPTCHA v2 key
googleMapsApiKey = "" #YOUR GOOGLE API KEY

# Sidebar Settings
[params.sidebar]
enable = 1 #SIDEBAR SHOW: [ 1 - yes, 0 - no ] For General page "Blog"
position = "right" #SIDEBAR POSITION: [ left, right ] For General page "Blog"
search = 1 #SIDEBAR SEARCH WIDGET: [ 1 - yes, 0 - no ]
latestPosts = 1 #SIDEBAR LATEST POSTS WIDGET: [ 1 - yes, 0 - no ]
categories = 1 #SIDEBAR CATEGORIES TAXONOMY WIDGET: [ 1 - yes, 0 - no ]
tags = 1 #SIDEBAR TAG TAXONOMY WIDGET: [ 1 - yes, 0 - no ]



# Portfolio Settings (Filter)
[params.portfolio]
[[params.portfolio.filters]]
name = "Sponsored-Events"
slug = "Sponsored-Events"
[[params.portfolio.filters]]
name = "Action-Sports"
slug = "Action-Sports"
[[params.portfolio.filters]]
name = "Industrial"
slug = "Industrial"
[[params.portfolio.filters]]
name = "Landscapes"
slug = "Landscapes"
[[params.portfolio.filters]]
name = "Nature"
slug = "Nature"

# Footer Settings
[params.footer]
copyright = "Edited by J "


# Sitemap Settings
[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[outputs]
home = ["HTML", "RSS", "JSON"]
